name: hele_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0
environment:
  sdk: '>=3.4.0 <4.0.0' # DartSDK

# 生产环境依赖
dependencies:
  flutter:
    sdk: flutter

  # 国际化
  flutter_localizations: # 国际化
    sdk: flutter
  intl: ^0.19.0 # 国际化

  # 界面UI
  cupertino_icons: ^1.0.6 # icon
  font_awesome_flutter: ^10.7.0 # icon
  auto_size_text: ^3.0.0 # 文本自适应
  expand_widget: ^3.1.1 # 文本折叠
  loading_animation_widget: ^1.2.1 # 加载动画
  fl_chart: ^0.68.0 # 图表
  flutter_smart_dialog: ^4.9.6+1 # 弹窗
  custom_sliding_segmented_control: ^1.8.3 # 分段器
  gap: ^3.0.1 # 间隔

  flutter_tilt: ^3.0.0 # 倾斜视差
  skeletonizer: ^1.2.0 # 骨架屏

  # 网络请求
  dio: ^5.4.3+1 # 网络请求
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.1.1
  connectivity_plus: ^6.0.1
  dio_http2_adapter: ^2.3.1+1

  # 开发工具
  cached_network_image: ^3.3.1 # 图片缓存
  flutter_screenutil: ^5.9.0 # 屏幕适配
  flutter_svg: ^2.0.10+1 # svg显示
  easy_refresh: ^3.4.0 # 下拉刷新
  url_launcher: ^6.2.6 # url跳转
  easy_debounce: ^2.0.3 # 防抖
  share_plus: ^9.0.0 # 分享
  logger: ^2.3.0 # log
  nil: ^1.1.1 # 占位符

  # 状态管理
  get: ^4.6.6 # 路由 & 状态管理
  provider: ^6.1.2 # 状态管理

  # 本地存储
  shared_preferences: ^2.2.3 # 本地状态存储

# 开发环境依赖
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  flutter_launcher_icons: ^0.13.1 # 应用图标生成

flutter:
  uses-material-design: true

  assets:
    - assets/images/svg/

# 应用图标生成
flutter_launcher_icons:
  android: "launcher_icon"
  min_sdk_android: 21
  ios: true
  image_path: "assets/images/icon/hele.png"

# 国际化配置
flutter_intl:
  generate: true
#  enabled: true
  # 自定义生成配置
  arb-dir: lib/l10n
  format: true
  output-class: S
  output-dir: lib/l10n/gen
  output-localization-file: app_g.dart
  template-arb-file: app_en.arb
  synthetic-package: false
  nullable-getter: false
  untranslated-messages-file: lib/l10n/gen/app_g_untranslated.json
